### ISSUE TITLE
There are no Adobe Updates available (Acrobat/Reader)

### ISSUE THREAD

**Issue by wreck-gar** [jmahlman/uarts-scripts#1]
Hi, I’ve run into a couple of issues with the Adobe-RUMWithProgress-jamfhelper.sh script. 

I needed to change the location of the rumlog as the folder didn’t exist. No biggie.

When there are only Acrobat/Reader updates available the grep (on line 113) won’t find any updates to present to the user. This is because the wording is slightly different.

**For Acrobat/Reader**

_Following Acrobat/Reader updates are applicable on the system :_ 

**For other Adobe apps;**

_Following Updates are applicable on the system :_

So I have changed line 113 to the following to make it work.

if [ "$(grep "pdates are applicable on the system" "$rumlog")" ] ; then

**Comment by jmahlman** [comment]
I'll have to check, but adding -i to ignore case should work also.
`if [ "$(grep -i "updates are applicable on the system" "$rumlog")" ] ; then`
