### ISSUE TITLE
Log file location is not created by default

### ISSUE THREAD

**Issue by JuiceMacAdmin** [jmahlman/uarts-scripts#3]
Had an issue running the Adobe-RUMwithprogress-jamfhelper script at first. The AdobeRUMUpdatesLog location is not created by default, & causes failure. EndUser popup displays "No available updates", even tho running RUM list in terminal did show updates available. Jamf log pulled errors starting with writing to the Log file location. 

Script result: touch: /Library/Application Support/CustomAdobeUpdater/AdobeRUMUpdatesLog.log: No such file or directory
/Library/Application Support/JAMF/tmp/Adobe-RUMwithProgress:83: no such file or directory: /Library/Application Support/CustomAdobeUpdater/AdobeRUMUpdatesLog.log
sed: /Library/Application Support/CustomAdobeUpdater/AdobeRUMUpdatesLog.log: No such file or directory
grep: /Library/Application Support/CustomAdobeUpdater/AdobeRUMUpdatesLog.log: No such file or directory

**Comment by JuiceMacAdmin** [comment]
This may now be working for me now. Added mkdir to create the folder first, things seem like they are working properly!

#Set the log path
logpath="/Library/Application Support/CustomAdobeUpdater"
#Ensure logFile can be written
if [ ! -d "${logpath}" ]; then
mkdir "${logpath}"
fi

**Comment by jmahlman** [comment]
Check this out and see if it helps. I've moved the logging stuff into a function and cleaned up some other code.

**Comment by jmahlman** [comment]
Resolved

**Comment by jmahlman** [comment]
Resolved in last push.
